///////////////////////////////////////////////////////////////////////
// BEToolbox
// Copyright © 1999-2017  Washington State Department of Transportation
//                        Bridge and Structures Office
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the Alternate Route Open Source License as 
// published by the Washington State Department of Transportation, 
// Bridge and Structures Office.
//
// This program is distributed in the hope that it will be useful, but 
// distribution is AS IS, WITHOUT ANY WARRANTY; without even the implied 
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See 
// the Alternate Route Open Source License for more details.
//
// You should have received a copy of the Alternate Route Open Source 
// License along with this program; if not, write to the Washington 
// State Department of Transportation, Bridge and Structures Office, 
// P.O. Box  47340, Olympia, WA 98503, USA or e-mail 
// Bridge_Support@wsdot.wa.gov
///////////////////////////////////////////////////////////////////////

// BEToolbox.idl : IDL source for BEToolbox
//

// This file will be processed by the MIDL tool to
// produce the type library (BEToolbox.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "PGSuperIEPlugin.idl";  // for the Importer/Exporter plugins

[
	uuid(B00EE67C-9FBF-42ef-8B80-CECD5AE5CC23),
	version(1.0),
	helpstring("BEToolbox 1.0 Type Library")
]
library BEToolboxLib
{
	importlib("stdole2.tlb");
	[
		uuid(B5E128D4-78F3-48e0-970E-812C2281EE4E),
		helpstring("BEToolboxPlugin Class")
	]
	coclass BEToolboxPlugin
	{
		[default] interface IUnknown;
	};

   [
      uuid(8BC4CCD2-35D5-4f2c-AA18-0E2D58FF5C3A)
   ]
   coclass BEToolboxComponentInfo
   {
      interface IUnknown;
   }

   [
		uuid(E89CC143-53C9-43df-B1B4-E522769DE29B),
		helpstring("CurvelExporter Class")
	]
	coclass CurvelExporter
	{
		[default] interface IPGSDataExporter;
	};
	[
		uuid(E56801AC-B583-4e9e-A2D8-2AA64079BE15),
		helpstring("CurvelImporter Class")
	]
	coclass CurvelImporter
	{
		[default] interface IPGSDataImporter;
	};

  	[
		uuid(16A21688-25B4-4118-ABF4-DD6D4983A2CD),
		helpstring("GenCompeExporter Class")
	]
	coclass GenCompExporter
	{
		[default] interface IPGSDataExporter;
	};

   [
		uuid(FF96408C-27B3-4288-8A44-6F80652BE187),
		helpstring("PGStableExporter Class")
	]
	coclass PGStableExporter
	{
		[default] interface IPGSDataExporter;
	};
};
