//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BEToolbox.rc
//
#define IDS_PROJNAME                    100
#define IDR_BETOOLBOX                   101
#define IDR_GENCOMP                     102
#define IDR_BETOOLBOXPLUGIN             103
#define IDR_BOXGDR                      104
#define IDD_BOXGDR                      104
#define IDR_BETOOLBOXCOMPONENTINFO      105
#define IDD_GENCOMP                     105
#define IDD_GIRCOMP                     106
#define IDD_GIRCOMP_TOP                 106
#define IDR_CURVELEXPORTER              106
#define IDR_GIRCOMP                     107
#define IDD_GIRCOMP_LEFT                107
#define IDR_CURVELIMPORTER              107
#define IDR_ULTCOL                      108
#define IDD_ULTCOL                      108
#define IDR_GENCOMPEXPORTER             108
#define IDD_PGSTABLEGIRDERVIEW          109
#define IDD_PGSTABLELIFTINGVIEW         110
#define IDD_PGSTABLEHAULINGVIEW         111
#define IDD_PGSTABLEEFFECTIVEPRESTRESSDLG 113
#define IDR_PGSTABLEEXPORTER            114
#define IDD_SPECTRA                     115
#define IDR_SPECTRA                     116
#define IDB_SPECTRA                     117
#define IDI_WSDOT                       200
#define IDC_UPDATE                      201
#define IDC_EXPORT                      202
#define IDR_TOOLBAR                     207
#define IDR_PGSTOOLBAR                  208
#define IDR_CURVEL                      209
#define IDD_CURVEL_WIZ_1                210
#define IDB_CURVEL_HEADER               211
#define IDB_CURVEL_WATERMARK            212
#define IDD_CURVEL_WIZ_2                213
#define IDD_CURVEL_WIZ_3                214
#define IDD_PRISMATIC_GIRDER            215
#define IDC_US                          216
#define IDD_NONPRISMATIC_GIRDER         216
#define IDB_PGSTABLE                    217
#define IDC_SI                          218
#define IDC_SCHEMATIC                   219
#define IDC_ADD                         220
#define IDC_REMOVE                      221
#define IDC_PRIMARY_SHAPE_GRID          222
#define IDC_SECONDARY_SHAPE_GRID        223
#define IDC_ADD_PRIMARY                 224
#define IDC_REMOVE_PRIMARY              225
#define IDC_ADD_SECONDARY               226
#define IDC_REMOVE_SECONDARY            227
#define IDC_N                           228
#define IDC_G1                          229
#define IDC_G1_UNIT                     230
#define IDC_CROWN_OFFSET                230
#define IDC_G2                          231
#define IDC_CROWN_OFFSET_UNIT           231
#define IDC_G2_UNIT                     232
#define IDC_CROWN_OFFSET_LABEL          232
#define IDC_LENGTH                      233
#define IDC_SUPERELEVATION_LABEL        233
#define IDC_LENGTH_UNIT                 234
#define IDC_STATION_LABEL_1             234
#define IDC_PVI_STATION                 235
#define IDC_STATION_1                   235
#define IDC_PVI_ELEVATION               236
#define IDC_LEFT_SLOPE_1                236
#define IDC_PVI_ELEVATION_UNIT          237
#define IDC_RIGHT_SLOPE_1               237
#define IDC_CROWN_OPTION                238
#define IDC_LEFT_SLOPE_UNIT_1           239
#define IDC_RIGHT_SLOPE_LABEL_1         240
#define IDC_RIGHT_SLOPE_UNIT_1          241
#define IDC_STATION_LABEL_2             242
#define IDC_STATION_2                   243
#define IDC_LEFT_SLOPE_2                244
#define IDC_LEFT_SLOPE_UNIT_2           245
#define IDC_RIGHT_SLOPE_LABEL_2         246
#define IDC_RIGHT_SLOPE_2               247
#define IDC_RIGHT_SLOPE_UNIT_2          248
#define IDC_STATION_LABEL_3             249
#define IDC_STATION_3                   250
#define IDR_ULTCOLTOOL                  250
#define IDC_LEFT_SLOPE_3                251
#define IDR_BOXGDRTOOL                  251
#define IDC_LEFT_SLOPE_UNIT_3           252
#define IDR_GENCOMPTOOL                 252
#define IDC_RIGHT_SLOPE_LABEL_3         253
#define IDR_GIRCOMPTOOL                 253
#define IDC_RIGHT_SLOPE_3               254
#define IDR_CURVELTOOL                  254
#define IDC_RIGHT_SLOPE_UNIT_3          255
#define IDR_PGSTABLETOOL                255
#define IDC_LEFT_SLOPE_LABEL_1          256
#define IDR_SPECTRATOOL                 256
#define IDC_LEFT_SLOPE_LABEL_2          257
#define IDC_LEFT_SLOPE_LABEL_3          258
#define IDC_INDIVIDUAL_STATIONS         259
#define IDC_INDIVIDUAL_STATION_ADD      260
#define IDC_INDIVIDUAL_STATION_REMOVE   261
#define IDC_STATION_RANGE               262
#define IDC_IMAGE                       262
#define IDC_STATION_RANGE_ADD           263
#define IDC_ECL                         263
#define IDC_INDIVIDUAL_STATION_REMOVE2  264
#define IDC_STATION_RANGE_REMOVE        264
#define IDC_ETL                         264
#define IDC_WTF                         264
#define IDC_SKEW_LINE                   265
#define IDC_HG                          265
#define IDC_SKEW_LINE_ADD               266
#define IDC_HG_UNIT                     266
#define IDC_STATION_RANGE_REMOVE2       267
#define IDC_SKEW_LINE_REMOVE            267
#define IDC_WTF_UNIT                    267
#define IDC_WBF                         268
#define IDC_WBF_UNIT                    269
#define IDC_AREA                        270
#define IDC_AREA_UNIT                   271
#define IDC_IX                          272
#define IDC_IX_UNIT                     273
#define IDC_IY                          274
#define IDC_IY_UNIT                     275
#define IDC_L                           276
#define IDC_L_UNIT                      277
#define IDC_YTOP                        278
#define IDC_YTOP_UNIT                   279
#define IDC_FPE_PERM                    280
#define IDC_IXY                         280
#define IDC_FPE_PERM_UNIT               281
#define IDC_XLEFT_UNIT                  281
#define IDC_XLEFT                       282
#define IDC_E1                          282
#define IDC_YTOP2                       282
#define IDC_IXY_UNIT                    283
#define IDC_E1_UNIT                     283
#define IDC_E2                          284
#define IDC_E2_UNIT                     285
#define IDC_FPE_TEMP                    286
#define IDC_FPE_TEMP_UNIT               287
#define IDC_E3                          288
#define IDC_E3_UNIT                     289
#define IDC_HP                          290
#define IDC_YS                          295
#define IDC_YS_UNIT                     296
#define IDC_XH1                         297
#define IDC_YH1                         298
#define IDC_YH1_UNIT                    299
#define IDC_XH2                         300
#define IDB_CURVEL                      300
#define IDC_DIAMETER                    301
#define IDC_YH2                         301
#define IDB_GENCOMP                     301
#define IDC_YH2_UNIT                    302
#define IDC_XH1_UNIT                    303
#define IDC_COVER                       304
#define IDC_XH2_UNIT                    304
#define IDC_AS                          305
#define IDC_XH3                         305
#define IDC_FC                          306
#define IDC_YH3                         306
#define IDC_ES                          307
#define IDC_YH3_UNIT                    307
#define IDC_XH3_UNIT                    308
#define IDC_FY                          309
#define IDC_YTEMP                       309
#define IDC_DIAMETER_UNIT               310
#define IDC_YS_UNIT2                    310
#define IDC_YTEMP_UNIT                  310
#define IDC_FC_UNIT                     311
#define IDC_STRAND_LAYOUT               311
#define IDC_COVER_UNIT                  312
#define IDC_DENSITY                     312
#define IDC_AS_UNIT                     313
#define IDC_XH4                         313
#define IDC_ES_UNIT                     314
#define IDC_YH4                         314
#define IDC_FY_UNIT                     315
#define IDC_YH4_UNIT                    315
#define IDC_XH4_UNIT                    316
#define IDC_DENSITY_UNIT                317
#define IDC_FPE_STRAIGHT                318
#define IDC_FPE_STRAIGHT_UNIT           319
#define IDC_FPE_HARPED                  320
#define IDC_DENSITY_WITH_REBAR          320
#define IDC_FPE_HARPED_UNIT             321
#define IDC_DENSITY_WITH_REBAR_UNIT     321
#define IDC_COMPUTE_EC                  323
#define IDC_EC                          324
#define IDC_EC_UNIT                     325
#define IDC_FR_COEFFICIENT              326
#define IDC_FR_COEFFICIENT_UNIT         327
#define IDC_SWEEP_TOLERANCE             328
#define IDC_SWEEP_TOLERANCE_UNIT        329
#define IDC_LATERAL_SWEEP_INCREMENT     330
#define IDC_LATERAL_SWEEP_INCREMENT_UNIT 331
#define IDC_SUPPORT_PLACEMENT_TOLERANCE 332
#define IDC_SUPPORT_PLACEMENT_TOLERANCE_UNIT 333
#define IDC_LIFT                        334
#define IDC_LIFT_UNIT                   335
#define IDC_RESULTS                     336
#define IDC_IMPACT_UP                   337
#define IDC_IMPACT_UP_UNIT              338
#define IDC_IMPACT_DOWN                 339
#define IDC_IMPACT_DOWN_UNIT            340
#define IDC_LIFT_ANGLE                  341
#define IDC_LIFT_ANGLE_UNIT             342
#define IDC_WIND_PRESSURE               343
#define IDC_WIND_PRESSURE_UNIT          344
#define IDC_YRA                         345
#define IDC_YRA_UNIT                    346
#define IDC_CAMBER                      350
#define IDC_CAMBER_UNIT                 351
#define IDC_LEFT_BUNK                   353
#define IDC_LEFT_BUNK_UNIT              354
#define IDC_RIGHT_BUNK                  355
#define IDC_RIGHT_BUNK_UNIT             356
#define IDC_VELOCITY                    357
#define IDC_VELOCITY_UNIT               358
#define IDC_RADIUS                      359
#define IDC_RADIUS_UNIT                 360
#define IDC_PRISMATIC                   361
#define IDC_NONPRISMATIC                362
#define IDC_STATIC_BOUNDS               363
#define IDC_SUPERELEVATION              364
#define IDC_LIFTING_FS_CRACKING         364
#define IDC_POINT_LOAD_GRID             365
#define IDC_HAULING_FS_CRACKING         365
#define IDC_ADD_LOAD                    366
#define IDC_K1                          366
#define IDC_STRESS_POINT_GRID           366
#define IDC_REMOVE_LOAD                 367
#define IDC_GIRDER_SECTION_GRID         368
#define IDC_ADD_SECTION                 369
#define IDC_REMOVE_SECTION              370
#define IDC_K2                          371
#define IDC_YH1_MEASURE                 372
#define IDC_YH2_MEASURE                 373
#define IDC_WCC                         373
#define IDC_YH3_MEASURE                 374
#define IDC_WCC_UNIT                    374
#define IDC_YH4_MEASURE                 375
#define IDC_EDIT3                       375
#define IDC_KTHETA                      375
#define IDC_JOB                         375
#define IDC_YS_MEASURE                  376
#define IDC_KTHETA_UNIT                 376
#define IDC_YT_MEASURE                  377
#define IDC_HRC                         377
#define IDC_HRC_UNIT                    378
#define IDC_HGB                         379
#define IDC_HGB_UNIT                    380
#define IDC_USE_PGS_CRITERIA            381
#define IDC_PROJECT_CRITERIA            382
#define IDC_LIFTING_FS_FAILURE          383
#define IDC_HAULING_FS_FAILURE          385
#define IDC_EDIT_FPE                    386
#define IDC_FPE_GRID                    387
#define IDC_HELP                        388
#define IDC_GRAPH                       389
#define IDC_STRESS_GRAPH                389
#define IDC_SWEEP_TOLERANCE_LABEL       390
#define IDC_FS_GRAPH                    391
#define IDC_XFER_LENGTH                 394
#define IDC_XFER_LENGTH_UNIT            395
#define IDC_CHECK1                      396
#define IDC_RESTRICT_IMPACT             396
#define IDC_MAX_BUNK                    398
#define IDC_MAX_BUNK_UNIT               399
#define IDC_LEADING_OVERHANG            400
#define IDC_LEADING_OVERHANG_UNIT       401
#define IDC_MAX_GIRDER_WEIGHT_UNIT      402
#define IDC_CF_TYPE                     403
#define IDC_ENGINEER                    404
#define IDC_COMPANY                     405
#define IDC_COMMENTS                    406
#define IDC_MATERIAL_GROUP              407
#define IDC_DRAG_COEFFICIENT            408
#define IDC_WIND_TYPE                   409
#define IDC_CROWN_SLOPE                 410
#define IDC_IMPACT_USAGE                411
#define IDC_CROWN_SLOPE_UNIT            412
#define IDC_SUPERELEVATION_UNIT         413
#define IDC_HAULING_TENSION_CROWN       414
#define IDC_HAULING_TENSION_CROWN_UNIT  415
#define IDC_CHECK_HAULING_TENSION_MAX_CROWN 416
#define IDC_HAULING_TENSION_MAX_CROWN   417
#define IDC_HAULING_TENSION_MAX_CROWN_UNIT 418
#define IDC_HAULING_TENSION_WITH_REBAR_CROWN 419
#define IDC_HAULING_TENSION_WITH_REBAR_CROWN_UNIT 420
#define IDC_PS_METHOD                   421
#define IDC_XFER_LENGTH_LABEL           422
#define IDC_YS_LABEL                    423
#define IDC_YH1_LABEL                   424
#define IDC_HP_LABEL                    426
#define IDC_YTEMP_LABEL                 427
#define IDC_SS_LABEL                    428
#define IDC_HS_LABEL                    429
#define IDC_TS_LABEL                    430
#define IDC_HP_UNIT                     431
#define IDC_YS_MEASURE_LABEL            432
#define IDC_XH1_LABEL                   433
#define IDC_XH2_LABEL                   434
#define IDC_XH3_LABEL                   435
#define IDC_YH3_LABEL                   436
#define IDC_XH4_LABEL                   437
#define IDC_YH4_LABEL                   438
#define IDC_FACE_LABEL                  439
#define IDC_YT_MEASURE_LABEL            440
#define IDC_FPE_NOTE                    441
#define IDC_SPEC                        443
#define IDC_HAUL_TRUCK                  444
#define IDC_COMBO1                      445
#define IDC_GIRDER_LIST                 445
#define IDC_SITE_CLASS                  445
#define IDC_LATITUDE                    446
#define IDC_LONGITUDE                   447
#define IDC_LAT_RANGE                   448
#define IDC_LNG_RANGE                   449
#define IDC_DESCRIPTION                 450
#define IDC_CAMBER_MULTIPLIER           452
#define IDC_PRECAMBER                   453
#define IDC_PRECAMBER_UNIT              454
#define IDC_COMPUTE_STRESS_POINTS       457
#define IDC_DEFINE_STRESS_POINTS        458
#define IDC_EX                          459
#define IDC_EX_UNIT                     460
#define IDC_LATERAL_CAMBER              461
#define IDC_LATERAL_CAMBER_UNIT         462
#define IDC_EX_LABEL                    463
#define IDC_EDIT1                       465
#define IDC_LIFTING_PEAK_COMPRESSION    465
#define IDC_LIFTING_GLOBAL_COMPRESSION  466
#define IDC_LIFTING_GLOBAL_COMPRESSION_UNIT 467
#define IDC_LIFTING_PEAK_COMPRESSION_UNIT 468
#define IDC_HAULING_GLOBAL_COMPRESSION  468
#define IDC_HAULING_GLOBAL_COMPRESSION_UNIT 469
#define IDC_HAULING_PEAK_COMPRESSION    470
#define IDC_HAULING_GLOBAL_COMPRESSION_UNIT2 471
#define IDC_HAULING_PEAK_COMPRESSION_UNIT 471
#define IDC_SWEEP_GROWTH                472
#define IDC_SWEEP_GROWTH_UNIT           473
#define IDC_CONSTANT_FPE                500
#define IDR_PGSTABLE                    500
#define IDC_VARIABLE_FPE                501
#define IDC_MAX_GIRDER_WEIGHT           502
#define IDC_YH2_LABEL                   525
#define IDD_ABOUTBOX                    999
#define IDC_VERSION                     1002
#define IDC_COPYRIGHT                   1003
#define IDC_APPICON                     1005
#define IDC_LIFTING_COMPRESSION         1126
#define IDC_LIFTING_TENSION             1127
#define IDC_CHECK_LIFTING_TENSION_MAX   1129
#define IDC_LIFTING_TENSION_MAX         1130
#define IDC_LIFTING_TENSION_MAX_UNIT    1131
#define IDC_LIFTING_COMPRESSION_UNIT    1132
#define IDC_HAULING_TENSION             1134
#define IDC_LIFTING_TENSION_WITH_REBAR  1135
#define IDC_HAULING_TENSION_SUPER       1135
#define IDC_LIFTING_TENSION_UNIT        1136
#define IDC_LIFTING_TENSION_WITH_REBAR_UNIT 1137
#define IDC_HAULING_TENSION_UNIT        1138
#define IDC_CHECK_HAULING_TENSION_MAX   1139
#define IDC_HAULING_TENSION_MAX         1140
#define IDC_HAULING_TENSION_MAX_UNIT    1141
#define IDC_HAULING_TENSION_WITH_REBAR  1142
#define IDC_HAULING_TENSION_WITH_REBAR_UNIT 1143
#define IDC_HAULING_TENSION_SUPER_UNIT  1144
#define IDC_CHECK_HAULING_TENSION_MAX_SUPER 1145
#define IDC_HAULING_TENSION_MAX_SUPER   1146
#define IDC_HAULING_TENSION_MAX_SUPER_UNIT 1147
#define IDC_HAULING_TENSION_WITH_REBAR_SUPER 1148
#define IDC_HAULING_TENSION_WITH_REBAR_SUPER_UNIT 1149
#define IDC_DIMENSIONS                  1156
#define IDC_BROWSER                     1177
#define IDC_STATIC_ACSCS                1289
#define IDC_STATIC_ACSTS                1290
#define IDC_STATIC_ACSSB                1291
#define IDC_STATIC_ACSCS2               1292
#define IDC_STATIC_ACSTS2               1293
#define IDC_STATIC_ACSCS3               1293
#define IDC_STATIC_ACSSB2               1294
#define IDC_STATIC_ACSSB3               1295
#define IDC_STATIC_ACSTS3               1296
#define IDC_WSDOT                       1666
#define IDC_TXDOT                       1668
#define IDC_GIRDER                      1781
#define ID_REFRESH_REPORT               36864
#define ID_HELP_ABOUTBETOOLBOX          36865

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        224
#define _APS_NEXT_COMMAND_VALUE         36871
#define _APS_NEXT_CONTROL_VALUE         470
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
