//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BEToolbox.rc
//
#define IDS_PROJNAME                    100
#define IDR_BETOOLBOX                   101
#define IDR_GENCOMP                     102
#define IDR_BETOOLBOXPLUGIN             103
#define IDR_BOXGDR                      104
#define IDD_BOXGDR                      104
#define IDR_BETOOLBOXCOMPONENTINFO      105
#define IDD_GENCOMP                     105
#define IDD_GIRCOMP                     106
#define IDD_GIRCOMP_TOP                 106
#define IDR_GIRCOMP                     107
#define IDD_GIRCOMP_LEFT                107
#define IDR_ULTCOL                      108
#define IDD_ULTCOL                      108
#define IDI_WSDOT                       200
#define IDC_UPDATE                      202
#define IDR_TOOLBAR                     207
#define IDR_CURVEL                      209
#define IDD_CURVEL_WIZ_1                210
#define IDB_CURVEL_HEADER               211
#define IDB_CURVEL_WATERMARK            212
#define IDD_CURVEL_WIZ_2                213
#define IDD_CURVEL_WIZ_3                214
#define IDC_US                          216
#define IDC_SI                          218
#define IDC_SCHEMATIC                   219
#define IDC_ADD                         220
#define IDC_REMOVE                      221
#define IDC_PRIMARY_SHAPE_GRID          222
#define IDC_SECONDARY_SHAPE_GRID        223
#define IDC_ADD_PRIMARY                 224
#define IDC_REMOVE_PRIMARY              225
#define IDC_ADD_SECONDARY               226
#define IDC_REMOVE_SECONDARY            227
#define IDC_N                           228
#define IDC_G1                          229
#define IDC_G1_UNIT                     230
#define IDC_CROWN_OFFSET                230
#define IDC_G2                          231
#define IDC_CROWN_OFFSET_UNIT           231
#define IDC_G2_UNIT                     232
#define IDC_CROWN_OFFSET_LABEL          232
#define IDC_LENGTH                      233
#define IDC_SUPERELEVATION_LABEL        233
#define IDC_LENGTH_UNIT                 234
#define IDC_STATION_LABEL_1             234
#define IDC_PVI_STATION                 235
#define IDC_STATION_1                   235
#define IDC_PVI_ELEVATION               236
#define IDC_LEFT_SLOPE_1                236
#define IDC_PVI_ELEVATION_UNIT          237
#define IDC_RIGHT_SLOPE_1               237
#define IDC_CROWN_OPTION                238
#define IDC_LEFT_SLOPE_UNIT_1           239
#define IDC_RIGHT_SLOPE_LABEL_1         240
#define IDC_RIGHT_SLOPE_UNIT_1          241
#define IDC_STATION_LABEL_2             242
#define IDC_STATION_2                   243
#define IDC_LEFT_SLOPE_2                244
#define IDC_LEFT_SLOPE_UNIT_2           245
#define IDC_RIGHT_SLOPE_LABEL_2         246
#define IDC_RIGHT_SLOPE_2               247
#define IDC_RIGHT_SLOPE_UNIT_2          248
#define IDC_STATION_LABEL_3             249
#define IDC_STATION_3                   250
#define IDC_LEFT_SLOPE_3                251
#define IDC_LEFT_SLOPE_UNIT_3           252
#define IDC_RIGHT_SLOPE_LABEL_3         253
#define IDC_RIGHT_SLOPE_3               254
#define IDC_RIGHT_SLOPE_UNIT_3          255
#define IDC_LEFT_SLOPE_LABEL_1          256
#define IDC_LEFT_SLOPE_LABEL_2          257
#define IDC_LEFT_SLOPE_LABEL_3          258
#define IDC_INDIVIDUAL_STATIONS         259
#define IDC_INDIVIDUAL_STATION_ADD      260
#define IDC_INDIVIDUAL_STATION_REMOVE   261
#define IDC_STATION_RANGE               262
#define IDC_IMAGE                       262
#define IDC_STATION_RANGE_ADD           263
#define IDC_ECL                         263
#define IDC_INDIVIDUAL_STATION_REMOVE2  264
#define IDC_STATION_RANGE_REMOVE        264
#define IDC_EDIT2                       264
#define IDC_ETL                         264
#define IDC_SKEW_LINE                   265
#define IDC_SKEW_LINE_ADD               266
#define IDC_STATION_RANGE_REMOVE2       267
#define IDC_SKEW_LINE_REMOVE            267
#define IDC_DIAMETER                    301
#define IDC_COVER                       304
#define IDC_AS                          305
#define IDC_FC                          306
#define IDC_ES                          307
#define IDC_FY                          309
#define IDC_DIAMETER_UNIT               310
#define IDC_FC_UNIT                     311
#define IDC_COVER_UNIT                  312
#define IDC_AS_UNIT                     313
#define IDC_ES_UNIT                     314
#define IDC_FY_UNIT                     315
#define IDD_ABOUTBOX                    999
#define IDC_VERSION                     1002
#define IDC_COPYRIGHT                   1003
#define IDC_APPICON                     1005
#define IDC_DIMENSIONS                  1156
#define IDC_WSDOT                       1666
#define IDC_TXDOT                       1668
#define ID_REFRESH_REPORT               36864
#define ID_HELP_ABOUTBETOOLBOX          36865
#define ID_HELP_ABOUTBETOOLBOX36866     36866

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        214
#define _APS_NEXT_COMMAND_VALUE         36867
#define _APS_NEXT_CONTROL_VALUE         265
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
